import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout/layout";
import LoginModel from "@/components/modals/LoginModal";
import RegisterModal from "@/components/modals/RegisterModal";
import { Toaster } from "react-hot-toast";
import EditModal from "@/components/modals/EditModal";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />

        <Layout>
          <EditModal />
          <LoginModel />
          <RegisterModal />
          {children}
        </Layout>
      </body>
    </html>
  );
}
