import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout/layout";
// import Modal from "@/components/layout/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Modal isOpen actionLable="submit" title="test model" /> */}
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
